In [4]:
import pandas as pd
print(pd.__version__)

3.0.0

In [6]:
data = pd.read_csv('top_rated_movies.csv')

In [8]:
data.head()
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 18520 entries, 0 to 18519
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    18520 non-null  int64
 1   id            18520 non-null  int64
 2   title         18520 non-null  str
 3   overview      18518 non-null  str
 4   release_date  18516 non-null  str
 5   popularity    18520 non-null  float64
 6   vote_average  18520 non-null  float64
 7   vote_count    18520 non-null  int64
dtypes: float64(2), int64(3), str(3)
memory usage: 1.1 MB

In [9]:
data.isnull()

,Unnamed: 0,id,title,overview,release_date,popularity,vote_average,vote_count
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
18515,False,False,False,False,False,False,False,False
18516,False,False,False,False,False,False,False,False
18517,False,False,False,False,False,False,False,False
18518,False,False,False,False,False,False,False,False
18519,False,False,False,False,False,False,False,False

In [10]:
data['title']

0                          The Shawshank Redemption
1                                     The Godfather
2                             The Godfather Part II
3                                  Schindler's List
4                                      12 Angry Men
                            ...
18515                            Father of the Year
18516                                     MacGruber
18517                                          I.T.
18518    A Nightmare on Elm Street: The Dream Child
18519                    Honey, We Shrunk Ourselves
Name: title, Length: 18520, dtype: str

In [13]:
data[['title','overview']]

,title,overview
0,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...
1,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
2,The Godfather Part II,In the continuing saga of the Corleone crime f...
3,Schindler's List,The true story of how businessman Oskar Schind...
4,12 Angry Men,The defense and the prosecution have rested an...
...,...,...
18515,Father of the Year,"Two college grads return to their hometown, wh..."
18516,MacGruber,Ex-special operative MacGruber is called back ...
18517,I.T.,"Mike Regan is a successful, self-made man who ..."
18518,A Nightmare on Elm Street: The Dream Child,The pregnant Alice finds Freddy Krueger striki...
18519,"Honey, We Shrunk Ourselves",The joke's on absent-minded scientist Wayne Sz...